builds:
  - binary: ukvisasponsors
    goos:
      - darwin
      - linux

    goarch:
      - arm64
      - amd64

    env:
      - CGO_ENABLED=0

    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: ukvisasponsors
    homepage: https://github.com/renatoaraujo/uk-visa-sponsors
    tap:
      owner: renatoaraujo
      name: homebrew-renatoaraujo
    commit_author:
      name: renatoaraujo
      email: me@renato.id

checksum:
  name_template: 'checksums.txt'