builds:
  - binary: ukvisasponsors
    main: ./cmd/cli/main.go
    goos:
      - darwin
      - linux

    goarch:
      - arm64
      - amd64

    env:
      - CGO_ENABLED=0

    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - name: ukvisasponsors
    homepage: https://github.com/renatoaraujo/uk-visa-sponsors
    download_strategy: CurlDownloadStrategy
    repository:
      owner: renatoaraujo
      name: homebrew-renatoaraujo
    commit_author:
      name: renatoaraujo

checksum:
  name_template: 'checksums.txt'