with-expecter: true
packages:
  renatoaraujo/uk-visa-sponsors/internal/sponsors:
    config:
      all: True
      dir: "{{.InterfaceDirRelative}}/mocks"
      outpkg: "mocks_test"
      filename: "{{.InterfaceName}}.go"
      mockname: "{{.InterfaceName}}"