with-expecter: true
dir: "{{.InterfaceDirRelative}}/mocks"
filename: "{{.InterfaceName}}.go"
outpkg: "mocks_test"
mockname: "{{.InterfaceName}}"
packages:
  renatoaraujo/uk-visa-sponsors/pkg/scraper:
    config:
      all: true
  renatoaraujo/uk-visa-sponsors/internal/sponsors:
    config:
      all: True
