// Code generated by mockery v2.34.1. DO NOT EDIT.

package mocks_test

import mock "github.com/stretchr/testify/mock"

// Processor is an autogenerated mock type for the Processor type
type Processor struct {
	mock.Mock
}

type Processor_Expecter struct {
	mock *mock.Mock
}

func (_m *Processor) EXPECT() *Processor_Expecter {
	return &Processor_Expecter{mock: &_m.Mock}
}

// ProcessRawData provides a mock function with given fields: _a0, _a1
func (_m *Processor) ProcessRawData(_a0 []byte, _a1 interface{}) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, interface{}) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Processor_ProcessRawData_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessRawData'
type Processor_ProcessRawData_Call struct {
	*mock.Call
}

// ProcessRawData is a helper method to define mock.On call
//   - _a0 []byte
//   - _a1 interface{}
func (_e *Processor_Expecter) ProcessRawData(_a0 interface{}, _a1 interface{}) *Processor_ProcessRawData_Call {
	return &Processor_ProcessRawData_Call{Call: _e.mock.On("ProcessRawData", _a0, _a1)}
}

func (_c *Processor_ProcessRawData_Call) Run(run func(_a0 []byte, _a1 interface{})) *Processor_ProcessRawData_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(interface{}))
	})
	return _c
}

func (_c *Processor_ProcessRawData_Call) Return(_a0 error) *Processor_ProcessRawData_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Processor_ProcessRawData_Call) RunAndReturn(run func([]byte, interface{}) error) *Processor_ProcessRawData_Call {
	_c.Call.Return(run)
	return _c
}

// NewProcessor creates a new instance of Processor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *Processor {
	mock := &Processor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
