name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}
          fetch-depth: '0'

      - name: Bump version and push tag
        id: version
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          MAJOR_STRING_TOKEN: "major:"
          MINOR_STRING_TOKEN: "minor:"
          PATCH_STRING_TOKEN: "patch:"

      - name: Create Release
        id: release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.version.outputs.new_tag }}
          token: ${{ secrets.RELEASE_TOKEN }}
